name: my-ai-app
version: 1.0.0
description: A simple frontend application for a medical assistant.
author: Your Name
license: MIT
dependencies:
  - react
  - react-dom
  - react-scripts
devDependencies:
  - webpack
  - babel-loader
  - eslint
scripts:
  start: react-scripts start
  build: react-scripts build
  test: react-scripts test
  eject: react-scripts eject
